version: "3.8"

services:
  backend:
    build: ./backend
    container_name: dropbox-lite-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/data  # Files stored here, mapped to TrueNAS dataset
      - ./uploads:/app/uploads
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: dropbox-lite-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: dropbox-lite-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data: