name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Test Python syntax
      run: |
        find backend -name "*.py" -exec python -m py_compile {} \;
        
    - name: Test imports
      run: |
        cd backend
        python -c "
        from main import app
        from routers.admin import router as admin_router  
        from routers.users import router as users_router
        from utils.email import send_welcome_email, send_password_reset_email
        print('✅ All imports successful')
        "
        
    - name: Test Docker builds
      run: |
        docker build -t cipherdrive-backend-test backend/
        docker build -t cipherdrive-frontend-test frontend/
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment notification
      run: |
        echo "🚀 Tests passed! Safe to deploy to TrueNAS SCALE"